fix in alternatives
38a8377 changed the signature of estimate_disp() to add the
frac and auto_frac_factor kwargs

this change in signatures was not propagated to the subclasses
defined in hic3defdr.analysis.alternatives, causing errors like:

TypeError: estimate_disp() got an unexpected keyword argument 'frac'

this commit fixes this issue by updating the signatures